### ISSUE TITLE
Posthog IP address whitelisting

### ISSUE THREAD

**Issue by ptrwtts** [PostHog/redshift-plugin#3]
Usually for these sorts of integrations, we need to whitelist certain IPs in our VPC security group. What are PostHog's IPs? Or does it work differently?

**Comment by Twixes** [comment]
Hey! Most importantly to answer this, how (where) is your PostHog instance deployed?

**Comment by ptrwtts** [comment]
Hi. I am just using the hosted version for now. Can redshift work with this?

**Comment by Twixes** [comment]
I see. Unfortunately we don't yet route PostHog traffic in a way that'd provide a stable way of whitelisting it. We have this on our radar now though: https://github.com/PostHog/posthog/issues/4581

**Comment by Hronom** [comment]
Per message here https://github.com/PostHog/redshift-plugin/issues/3#issuecomment-853819807 it's supported now

**Comment by Twixes** [comment]
Indeed, time to close this!
