### ISSUE TITLE
Write properties to a "super" type column

### ISSUE THREAD

**Issue by pauldambra** [PostHog/redshift-plugin#5]
Redshift provides the super column type to allow for loading semi-structured data including JSON

https://docs.aws.amazon.com/redshift/latest/dg/ingest-super.html

We load the event properties JSON into a varchar column but should load it into a super column

# querying a super column
![json_as_super](https://user-images.githubusercontent.com/984817/152322301-148ac865-7de9-49d9-beb8-a2d8d7b96818.gif)

# querying a varchar column
![json_as_varchar](https://user-images.githubusercontent.com/984817/152322307-87fcf948-b4eb-4329-90ea-d193d26fa9d3.gif)

**Comment by yakkomajuri** [comment]
Done in #7
